name: suno
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  sqflite: ^1.3.0+1
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.7+3
  flutter_vibrate: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  color: "000000"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconApp/suno.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/iconApp/suno_adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/netflix.png    
    - assets/adobe_creative.jpeg    
    - assets/apple_music.jpg 
    - assets/deezer.jpg
    - assets/globoplay.png
    - assets/looke.png    
    - assets/youtube_premium.jpg    
    - assets/viki.png
    - assets/apple_arcade.jpeg
    - assets/stadia.jpg
    - assets/psn.png
    - assets/xbox_live.jpg    
    - assets/xbox_gamepass.jpg
    - assets/nintendo_online.jpg
    - assets/disney_pluss.png
    - assets/hulu.png
    - assets/hbo.png    
    - assets/figma.png
    - assets/sketch.png       
    - assets/crunchyroll.jpg    
    - assets/ea_access.jpg
    - assets/linkedin_premium.jpg
    - assets/office.jpg
    - assets/telecine.jpg
    - assets/youtube_music.png
    - assets/adobe_logo.png
    - assets/kindle_unlimited.jpg
    - assets/amazon_primevideo.jpg
    - assets/spotify.jpg
    - assets/spotify2.jpg 
    - assets/spotify3.jpg
    - assets/spotify.png      
    - assets/zoom.jpeg
    - assets/apple_tv.jpg
    - assets/slack.jpg
    - assets/google_playmusic.png
    - assets/amazon_music.jpg    
    - assets/claro_musica.png
    - assets/napster.jpg
    - assets/rdio.jpg
    - assets/crackle.jpg
    - assets/fox_play.jpg
    - assets/tidal.png
    - assets/canva.jpg
    - assets/dribbble.png
    - assets/gsuite.jpg
    - assets/kinopop.jpg
    - assets/origin_access.jpg
    - assets/humble.jpg
    - assets/humbleM.png
    - assets/utomik.jpg
    - assets/utomik2.jpg
    - assets/verizon.jpg
    - assets/icloud.jpeg
    - assets/google_drive.jpg
    - assets/amazon_drive.jpg
    - assets/asus_webstorage.jpg
    - assets/dropbox.jpg
    - assets/wix.jpg
    - assets/vegas_pro.jpg
    - assets/vegas_pro.png
    - assets/trello.png
    - assets/team_viewer.png
    - assets/team_viewer.jpg
    - assets/bluehost.jpg
    - assets/godaddy.jpg
    - assets/hostgator.png
    - assets/hostinger.png
    - assets/kinghost.jpg
    - assets/locaweb.png
    - assets/weblink.png
    - assets/fundo/fundobotao.png
    - assets/fundo/fundo.png
    - assets/fundo/fundo2.png
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Stentiga
      fonts:
        - asset: assets/fonts/stentiga.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
